"""
Three-scenario evaluation harness (Section 7 of the project definition).

Compares, on the *same* engineered conjunction:

* ``no_cooperation`` — today's realistic status-quo stand-in: each operator
  only has degraded, public-tracking-quality knowledge of the other side's
  object (modelled as a larger, slowly-shrinking position uncertainty),
  and nothing at all is exchanged across the operator boundary.
* ``full_sharing`` — an unrealistic but useful upper bound: every operator
  sees every other operator's full-precision trajectory data directly.
* ``federated`` — the system proposed here: each operator has full-
  precision knowledge of *its own* asset (as it does today) and only an
  abstracted, threshold-gated signal crosses the boundary.

The headline result this harness is built to produce: federated matches
full-sharing's detection lead time while exposing 0% of raw trajectory
data (the same exposure level as no-cooperation) — see
``docs/sample_run.md`` (generated by ``scripts/run_demo.py``) for a worked
example.

A second sweep (:func:`robustness_sweep`) separately evaluates the
federation's aggregation strategies (Section 5/Enhancement 1) as the
fraction of dishonest reporting operators increases — this is where
"robustness of detection accuracy as the fraction of adversarial/dishonest
participants increases" (the fourth evaluation metric in Section 7) is
actually measured.
"""

from __future__ import annotations

from dataclasses import dataclass, asdict

import numpy as np

from .fleets import build_synthetic_fleets, inject_actor_encounter, _epoch_from_calendar
from .twin import propagate_window, screen_conjunctions, compute_pc, DEFAULT_PC_THRESHOLD
from .federation import (
    OperatorReport,
    mean_aggregate,
    trimmed_mean_aggregate,
    krum_aggregate,
    inject_adversarial_report,
    aggregation_error,
)

SIGMA_GOOD_KM = 0.5        # federated & full-sharing: your own precisely tracked asset
SIGMA_NOCOOP_FAR_KM = 3.0  # no-cooperation: degraded public-only tracking, far from TCA
SIGMA_NOCOOP_NEAR_KM = 0.5  # improves closer to TCA as more public tracking passes accumulate


def sigma_no_cooperation(lead_time_s: float, max_lead_time_s: float) -> float:
    """Simplified model: public-tracking precision improves linearly as the
    predicted TCA approaches, from a degraded far-out value to roughly the
    same near-term precision every scenario eventually gets."""
    if max_lead_time_s <= 0:
        return SIGMA_NOCOOP_NEAR_KM
    frac = max(0.0, min(1.0, lead_time_s / max_lead_time_s))
    return SIGMA_NOCOOP_NEAR_KM + frac * (SIGMA_NOCOOP_FAR_KM - SIGMA_NOCOOP_NEAR_KM)


def detection_lead_time(
    true_miss_distance_km: float,
    tca_offset_s: float,
    sigma_fn,
    threshold: float = DEFAULT_PC_THRESHOLD,
    step_s: float = 10.0,
) -> tuple[float, float]:
    """Scan forward from t=0 toward TCA; return (lead_time_s, first_detect_offset_s)
    for the first screening instant whose Pc estimate (using that regime's
    ``sigma_fn(lead_time_s)``) crosses ``threshold``. If it never crosses in
    time, lead_time_s is 0 (detected only at/after the event, i.e. too late
    to act).
    """
    t = 0.0
    while t <= tca_offset_s:
        lead = tca_offset_s - t
        sigma = sigma_fn(lead)
        pc = compute_pc(true_miss_distance_km, combined_sigma_km=sigma)
        if pc >= threshold:
            return lead, t
        t += step_s
    return 0.0, tca_offset_s


@dataclass
class ScenarioResult:
    name: str
    detection_lead_time_s: float
    raw_data_exposed_pct: float
    cross_operator_signal_shared: bool

    def as_dict(self):
        return asdict(self)


def run_three_scenario_comparison(seed: int = 42, tca_offset_min: float = 30.0) -> dict:
    """Build one engineered conjunction and evaluate all three scenarios
    against it. Returns {"conjunction": Conjunction, "scenarios": {name: ScenarioResult}}.
    """
    objects = build_synthetic_fleets(seed=seed)
    actor_a, actor_b = inject_actor_encounter(objects, tca_offset_min=tca_offset_min)
    epoch_days, jd0, fr0 = _epoch_from_calendar(2026, 9, 9, 0.0)

    duration_s = int(tca_offset_min * 60) + 600
    samples = propagate_window(objects, jd0, fr0, duration_s=duration_s, step_s=10.0)
    conjunctions = screen_conjunctions(objects, samples, screening_distance_km=25.0)
    actor_conj = next(
        c for c in conjunctions
        if {c.object_a.norad_id, c.object_b.norad_id} == {actor_a.norad_id, actor_b.norad_id}
    )

    tca_s = actor_conj.tca_offset_s
    miss_km = actor_conj.miss_distance_km

    lead_good, _ = detection_lead_time(miss_km, tca_s, sigma_fn=lambda lead: SIGMA_GOOD_KM)
    lead_nocoop, _ = detection_lead_time(
        miss_km, tca_s, sigma_fn=lambda lead: sigma_no_cooperation(lead, tca_s)
    )

    scenarios = {
        "no_cooperation": ScenarioResult(
            name="No Cooperation",
            detection_lead_time_s=lead_nocoop,
            raw_data_exposed_pct=0.0,
            cross_operator_signal_shared=False,
        ),
        "full_sharing": ScenarioResult(
            name="Full Data Sharing",
            detection_lead_time_s=lead_good,
            raw_data_exposed_pct=100.0,
            cross_operator_signal_shared=True,
        ),
        "federated": ScenarioResult(
            name="Federated (Proposed)",
            detection_lead_time_s=lead_good,
            raw_data_exposed_pct=0.0,
            cross_operator_signal_shared=True,
        ),
    }
    return {"conjunction": actor_conj, "scenarios": scenarios}


def robustness_sweep(
    n_operators: int = 10,
    n_trials: int = 40,
    adversary_fractions: tuple = (0.0, 0.1, 0.2, 0.3, 0.4),
    assumed_byzantine_tolerance: int = 2,
    attack_types=("spoof_high", "suppress", "sign_flip"),
    seed: int = 0,
) -> dict:
    """Sweep the fraction of dishonest operators from 0 to 40% and measure
    each aggregation strategy's error against the honest-only ground truth.

    ``assumed_byzantine_tolerance`` is fixed in advance (a design/config
    choice a real deployment would make without knowing the true attacker
    count) — Krum is expected to degrade gracefully, not perfectly, once
    the true adversary count exceeds it.
    """
    rng = np.random.default_rng(seed)
    results = {"mean": [], "trimmed_mean": [], "krum": []}

    for frac in adversary_fractions:
        n_adv = round(frac * n_operators)
        n_honest = n_operators - n_adv
        errs = {"mean": [], "trimmed_mean": [], "krum": []}
        for _ in range(n_trials):
            honest = [
                OperatorReport(operator=f"Op{i}", counts=rng.poisson(3, size=3).astype(float))
                for i in range(n_honest)
            ]
            adversaries = [
                inject_adversarial_report(
                    OperatorReport(operator=f"Adv{i}", counts=rng.poisson(3, size=3).astype(float)),
                    attack_type=attack_types[i % len(attack_types)],
                    magnitude=20.0,
                )
                for i in range(n_adv)
            ]
            all_reports = honest + adversaries
            if not all_reports or not honest:
                continue
            m_est = mean_aggregate(all_reports)
            t_est = trimmed_mean_aggregate(all_reports, trim_fraction=0.3)
            k_est = krum_aggregate(all_reports, n_byzantine=assumed_byzantine_tolerance)
            errs["mean"].append(aggregation_error(m_est, honest))
            errs["trimmed_mean"].append(aggregation_error(t_est, honest))
            errs["krum"].append(aggregation_error(k_est, honest))

        for key in results:
            results[key].append(float(np.mean(errs[key])) if errs[key] else float("nan"))

    return {"adversary_fractions": list(adversary_fractions), "mean_error": results["mean"],
            "trimmed_mean_error": results["trimmed_mean"], "krum_error": results["krum"]}
